### PR TITLE
fix: fix native optimization

### LINKED ISSUE #89: Error in macro enable_native_optimization
I got the error:
```
CMake Error at build/_deps/_project_options-src/src/Optimization.cmake:18 (target_compile_options):
  Cannot specify compile options for target "PRIVATE" which is not built by
  this project.
```

The reason is that the macro lacks a parameter to receive `project_name`.

### PR DESCRIPTION
**Pull request by aminya**
Fixes #89

### CODE REVIEW

**Comment by aminya** [comment]
> Thanks for the quick action! Will you generate a release for this fix?

You're welcome. Yes, I will. I have requested @ddalcino's review as well to confirm the bug fix.

**Comment by ljishen** [comment]
> > Thanks for the quick action! Will you generate a release for this fix?
> 
> You're welcome. Yes, I will. I have requested @ddalcino's review as well to confirm the bug fix.

Cool :)

**Comment by aminya** [comment]
I separated the questionable part of this PR. This can be merged as is.

**Review by ddalcino — COMMENTED** [review]
It’s too late now, but I’m approving this now anyway.

**Pull request merged**
